---
- name: 重启 containerd
  ansible.builtin.systemd_service:
    name: containerd
    state: restarted
    daemon_reload: true

- name: 重启 CRI-O
  ansible.builtin.systemd_service:
    name: crio
    state: restarted
    daemon_reload: true
